<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-27T10:09:57 IST" name="Default suite" finished-at="2021-12-27T10:10:22 IST" duration-ms="25458">
    <groups>
      <group name="Smokesiute">
        <method signature="ContactTestCaseTestNg.ContactTestcaseTest()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" name="ContactTestcaseTest" class="com.crm.contactTestcase1.ContactTestCaseTestNg"/>
      </group> <!-- Smokesiute -->
    </groups>
    <test started-at="2021-12-27T10:09:57 IST" name="Default test" finished-at="2021-12-27T10:10:22 IST" duration-ms="25458">
      <class name="com.crm.contactTestcase1.ContactTestCaseTestNg">
        <test-method is-config="true" signature="DBconnecetion()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:09:57 IST" name="DBconnecetion" finished-at="2021-12-27T10:09:57 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DBconnecetion -->
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:09:57 IST" name="LaunchBrowser" finished-at="2021-12-27T10:10:05 IST" duration-ms="8561" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:10:05 IST" name="loginToApp" finished-at="2021-12-27T10:10:09 IST" duration-ms="4241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="ContactTestcaseTest()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:10:09 IST" name="ContactTestcaseTest" finished-at="2021-12-27T10:10:18 IST" duration-ms="8841" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.crm.contactTestcase1.ContactTestCaseTestNg.ContactTestcaseTest(ContactTestCaseTestNg.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ContactTestcaseTest -->
        <test-method is-config="true" signature="logoutoffApp()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:10:19 IST" name="logoutoffApp" finished-at="2021-12-27T10:10:20 IST" duration-ms="1901" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutoffApp -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:10:20 IST" name="closeBrowser" finished-at="2021-12-27T10:10:22 IST" duration-ms="1659" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeDBconnection()[pri:0, instance:com.crm.contactTestcase1.ContactTestCaseTestNg@618425b5]" started-at="2021-12-27T10:10:22 IST" name="closeDBconnection" finished-at="2021-12-27T10:10:22 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBconnection -->
      </class> <!-- com.crm.contactTestcase1.ContactTestCaseTestNg -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
